language: java

sudo: false # run on container-based infrastructure

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - VARIANT=2.0
    - VARIANT=2.3
    - VARIANT=2.4
  global:
    # SIGNING_PASSWORD
    - secure: "GBvPdDAaMfr0iAYHzVxhMIBVHFanEPY+69CbEFijbZjhv8h0FPvuLos2p1K5/hbmNkQ1Hd2+CHsm3ErvXQHXtpXn0HmKvzSP7pnPk83iRNVGPieasvfnKiSohZeEplkAK6kbK8sZbjJRUFqUZtwyPtWfs244rCOo++D3KtfggzQ="
    # SONATYPE_OSS_PASSWORD
    - secure: "Y2PbI07I8M8k1qkwN671HdcLPPpnjATWya/m4PDIICioXkkdJrQzpj5x57efAJEWx2upI8PpgGm8ekUd2F/6l1rq0n4DnGHwGTNe1PDAXUw5qFt66RnqrfIVh2eUvPuQk6bXczLV39GksqqD1T/HS6KofknXpHKzk/JeCiiGoxI="
    # GITHUB_TOKEN
    - secure: "YhBI9LWk4AlRSOmt0aBo0TphuVIzHIVdPGClg35S1b2I6xbc0gRIVXb+ySBZIhFkqaicPFTjO2FXerXEr6SJwz5y3LvA5oBWJC4U/9FdegoP9PopZwiAKA0KLTuBMFrTAjTHAmwJePO7a8yqNCbjKfwEc9hbM64YU+sSXdUJfEU="

matrix:
  exclude:
    # Groovy 2.0 doesn't support Java 8
    - jdk: oraclejdk8
      env: VARIANT=2.0
    # Reduce Travis workload (currently 5 concurrent builds are allowed)
    # See travisCiBuild task for mandatory combinations
    - jdk: openjdk7
      env: VARIANT=2.0
    ## ensure docs only get published once otherwise it causes build to fail
    - jdk: openjdk7
      env: VARIANT=2.4
    - jdk: oraclejdk8
      env: VARIANT=2.3

install: true

script: ./gradlew --no-daemon travisCiBuild -Dvariant=$VARIANT -Dscan

notifications:
  slack:
    secure: eOht23SFXh9MayI/vIiez6pWvwYw/D92d8gvbQvRWtL4EumgA7aRW52roSCayKBg8HzYFUdylFyD2d1P8cgHBhdvIwq/aMSVa/5EsJ4fTlwJJEhS3aTPdGQqgv8XdRrE9WJ8S/yp7LbZXbEpGKKUqsjLYkTDM7SQJUJmvLz0X00=
