[versions]
groovy2 = '2.5.23'
groovy3 = '3.0.20'
groovy4 = '4.0.18'
jacoco = '0.8.11'
junit = '5.10.2'
asm = '9.6'
mockito4 = '4.11.0'
mockito5 = '5.10.0'

[libraries]
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asmUtil = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
bytebuddy = "net.bytebuddy:byte-buddy:1.14.11"
cglib = "cglib:cglib-nodep:3.3.0"
geantyref = "io.leangen.geantyref:geantyref:1.3.15"
h2database = "com.h2database:h2:2.2.224"
hamcrest = "org.hamcrest:hamcrest:2.2"
jaxb = "javax.xml.bind:jaxb-api:2.3.1"
junit4 = "junit:junit:4.13.2"
log4j = "log4j:log4j:1.2.17"
mockito4 = { module = "org.mockito:mockito-core", version.ref = "mockito4" }
mockito4inline = { module = "org.mockito:mockito-inline", version.ref = "mockito4" }
mockito5 = { module = "org.mockito:mockito-core", version.ref = "mockito5" }
objenesis = "org.objenesis:objenesis:3.3"
# This needs a classifier, but is has to be specified on the usage end https://melix.github.io/blog/2021/03/version-catalogs-faq.html#_why_can_t_i_use_excludes_or_classifiers
jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "jacoco" }
junit-bom =  { module = "org.junit:junit-bom",  version.ref = "junit" }
# to omit the version we have to use this syntax, the version is managed by the junit-bom
junit-jupiter.module = "org.junit.jupiter:junit-jupiter"
junit-platform-testkit.module = "org.junit.platform:junit-platform-testkit"
junit-platform-console.module = "org.junit.platform:junit-platform-console"

# just here so that renovate can figure out the dependencies
groovy-v2 = { module = "org.codehaus.groovy:groovy", version.ref="groovy2" }
groovy-v3 = { module = "org.codehaus.groovy:groovy", version.ref="groovy3" }
groovy-v4 = { module = "org.apache.groovy:groovy", version.ref="groovy4" }
